Models/Producto.cs
using System;
using System.Collections.Generic;

namespace Jiji.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Nombre { get; set; } = null!;

    public int Idorden { get; set; }

    public int Idcategoria { get; set; }

    public int Idempresa { get; set; }

    public decimal Valor { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Categoria IdcategoriaNavigation { get; set; } = null!;

    public virtual Empresa IdempresaNavigation { get; set; } = null!;

    public virtual Ordene IdordenNavigation { get; set; } = null!;
}

Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Mvc;
using Jiji.Models;

namespace Jiji.Controllers
{
    public class AdministradorController : Controller
    {
        private readonly TestContext _context;

        public AdministradorController(TestContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            var userRole = HttpContext.Session.GetInt32("UserRole");

            if (userRole == 1)
            {
                return View();
            }
            else if (userRole == 2)
            {
                return RedirectToAction("Index", "Cliente");
            }

            ViewData["ErrorMessage"] = "Acceso denegado. Solo los administradores pueden acceder a esta vista.";
            return View("Error");
        }

    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Jiji.Models;

namespace Jiji.Controllers
{
    public class ProductosController : Controller
    {
        private readonly TestContext _context;

        public ProductosController(TestContext context)
        {
            _context = context;
        }

        private IActionResult ValidacionRol()
        {
            var userRole = HttpContext.Session.GetInt32("UserRole");

            if (userRole == 1)
            {
                return null;
            }
            else if (userRole == 2)
            {
                return RedirectToAction("Index", "Cliente");
            }

            ViewData["ErrorMessage"] = "Acceso denegado. Solo los administradores pueden acceder a esta vista.";
            return View("Error");
        }

        public async Task<IActionResult> Index()
        {
            var result = ValidacionRol();
            if (result != null) return result;

            var productos = _context.Productos
                        .Include(p => p.IdordenNavigation)
                        .Include(p => p.IdcategoriaNavigation)
                        .Include(p => p.IdempresaNavigation)
                        .ToListAsync();
            return productos != null ?
                        View(await productos) :
                        Problem("Entity set 'JijiContext.Productos' is null.");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var result = ValidacionRol();
            if (result != null) return result;

            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            ViewBag.Ordenes = await _context.Ordenes.ToListAsync();
            ViewBag.Categorias = await _context.Categorias.ToListAsync();
            ViewBag.Empresas = await _context.Empresas.ToListAsync();

            return View(producto);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSave(int id, [Bind("Id,Nombre,Idorden,Idcategoria,Idempresa,Valor")] Producto producto)
        {
            var result = ValidacionRol();
            if (result != null) return result;

            var existingProducto = await _context.Productos.FindAsync(id);
            if (existingProducto == null)
            {
                return NotFound();
            }

            existingProducto.Nombre = producto.Nombre;
            existingProducto.Idorden = producto.Idorden;
            existingProducto.Idcategoria = producto.Idcategoria;
            existingProducto.Idempresa = producto.Idempresa;
            existingProducto.Valor = producto.Valor;
            existingProducto.UpdatedAt = DateTime.Now;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int? id)
        {
            var result = ValidacionRol();
            if (result != null) return result;

            if (id == null || _context.Productos == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.IdordenNavigation)
                .Include(p => p.IdcategoriaNavigation)
                .Include(p => p.IdempresaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }


        [HttpGet]
        public IActionResult Create()
        {
            var result = ValidacionRol();
            if (result != null) return result;

            ViewBag.Ordenes = _context.Ordenes.ToList();
            ViewBag.Categorias = _context.Categorias.ToList();
            ViewBag.Empresas = _context.Empresas.ToList();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Producto producto)
        {
            var result = ValidacionRol();
            if (result != null) return result;

            _context.Add(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var result = ValidacionRol();
            if (result != null) return result;
            
            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            _context.Productos.Remove(producto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Productos/Create.cshtml
@model Jiji.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" required />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idorden" class="control-label"></label>
                <select asp-for="Idorden" class="form-control" asp-items="@(new SelectList(ViewBag.Ordenes, "Id", "Nombre"))" required>
                    <option value="">Seleccione una orden</option>
                </select>
                <span asp-validation-for="Idorden" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idcategoria" class="control-label"></label>
                <select asp-for="Idcategoria" class="form-control" asp-items="@(new SelectList(ViewBag.Categorias, "Id", "Nombre"))" required>
                    <option value="">Seleccione una categoría</option>
                </select>
                <span asp-validation-for="Idcategoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idempresa" class="control-label"></label>
                <select asp-for="Idempresa" class="form-control" asp-items="@(new SelectList(ViewBag.Empresas, "Id", "Nombre"))" required>
                    <option value="">Seleccione una empresa</option>
                </select>
                <span asp-validation-for="Idempresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" required />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Productos/Details.cshtml
@model Jiji.Models.Producto
@using Jiji.Helpers


@{
    ViewData["Title"] = "Detalles del Producto";
}

<h1>Detalles del Producto</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Idorden)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Idorden)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Idcategoria)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Idcategoria)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Idempresa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Idempresa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayCurrency(Model.Valor, "es-CO")
            @Html.DisplayCurrency(Model.Valor, "en-US")
            @Html.DisplayCurrency(Model.Valor, "fr-FR")
            @Html.DisplayCurrency(Model.Valor, "ja-JP")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

Views/Productos/Edit.cshtml
@model Jiji.Models.Producto

@{
    ViewData["Title"] = "Editar Producto";
}

<h1>Editar Producto</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditSave">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Idorden" class="control-label"></label>
                <select asp-for="Idorden" class="form-control"
                    asp-items="@(new SelectList(ViewBag.Ordenes, "Id", "Nombre"))">
                    <option value="">Seleccione una Orden</option>
                </select>
                <span asp-validation-for="Idorden" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Idcategoria" class="control-label"></label>
                <select asp-for="Idcategoria" class="form-control"
                    asp-items="@(new SelectList(ViewBag.Categorias, "Id", "Nombre"))">
                    <option value="">Seleccione una Categoría</option>
                </select>
                <span asp-validation-for="Idcategoria" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Idempresa" class="control-label"></label>
                <select asp-for="Idempresa" class="form-control"
                    asp-items="@(new SelectList(ViewBag.Empresas, "Id", "Nombre"))">
                    <option value="">Seleccione una Empresa</option>
                </select>
                <span asp-validation-for="Idempresa" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Productos/Index.cshtml
@model IEnumerable<Jiji.Models.Producto>
@using Jiji.Helpers

@{
    ViewData["Title"] = "Productos";
}

<h1>Producto</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Crear Nueva Producto</a>
</p>
<div>
    <a asp-controller="Administrador" asp-action="Index">Back to List</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idorden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idcategoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idempresa)
            </th>
            <th>
                Valor CO
            </th>
            <th>

                Valor US
            </th>
            <th>
                Valor FR
            </th>
            <th>
                Valor JP
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdordenNavigation.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdcategoriaNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdempresaNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayCurrency(item.Valor, "es-CO")
                </td>
                <td>
                    @Html.DisplayCurrency(item.Valor, "es-US")
                </td>
                <td>
                    @Html.DisplayCurrency(item.Valor, "es-FR")
                </td>
                <td>
                    @Html.DisplayCurrency(item.Valor, "es-JP")
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Id">Details</a> |
                    <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-@item.Id">Delete</a>
                </td>
            </tr>

            <div class="modal fade" id="deleteModal-@item.Id" tabindex="-1" aria-labelledby="deleteModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirmar Eliminación</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            ¿Estás seguro de que deseas eliminar esta producto?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <form asp-action="Delete" method="post" asp-route-id="@item.Id">
                                <button type="submit" class="btn btn-danger">Eliminar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
        
    </tbody>
</table>